apiVersion: v1
kind: Service
metadata:
  name: {{ template "celery.fullname" . }}-flower
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    component: "celery-flower"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.celery.flower.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
    component: "celery-flower"
