apiVersion: v1
kind: ServiceAccount
{{- if .Values.image.pullSecrets }}
imagePullSecrets: {{ toYaml .Values.image.pullSecrets | nindent 2 }}
{{- end }}
metadata:
  name: {{ template "celery.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    component: "celery"
