{{ $fullName := include "celery.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "celery.fullname" . }}-flower
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    component: "celery-flower"
{{- with .Values.celery.flower.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 | trim }}
{{- end }}
spec:
  {{- if and .Values.celery.flower.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.celery.flower.ingress.className }}
  {{- end }}
{{- with .Values.celery.flower.ingress.tls }}
  tls:
    {{ toYaml . | nindent 4 | trim }}
{{- end }}
  rules:
  {{- range .Values.celery.flower.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: {{ $fullName }}-flower
                port:
                  name: http
  {{- end }}
