{{- if .Values.cloudsqlProxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudsql.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    component: "cloudsqlproxy"
type: Opaque
data:
  cloudsql.json: |-
    {{ .Values.cloudsqlProxy.serviceAccountKey }}
{{- end -}}