{{- if .Values.cloudsqlProxy.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "cloudsql.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    component: "cloudsqlproxy"
spec:
  replicas: {{ .Values.cloudsqlProxy.replicaCount }}
  serviceName: cloudsqlproxy
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
      component: "cloudsqlproxy"
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
        component: "cloudsqlproxy"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - cloudsqlproxy
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 0.1
            memory: 100Mi
          requests:
            cpu: 0.01
            memory: 100Mi
        command: ["/cloud_sql_proxy",
                  "-instances={{ .Values.cloudsqlProxy.instance }}=tcp:0.0.0.0:5432",
                  "-credential_file=/secrets/cloudsql/cloudsql.json"]
        volumeMounts:
        - name: service-account-key
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: service-account-key
        secret:
          secretName: {{ template "cloudsql.fullname" . }}
{{- end }}
