apiVersion: v2
name: backend
version: 2.3.4
appVersion: v2.3.4
kubeVersion: "^1.18.0-0"
description: The StakeWise backend application.
type: application
keywords:
  - ethereum
  - blockchain
  - staking
home: https://stakewise.io/
sources:
  - https://github.com/tsudmi/backend/
dependencies:
  - name: postgresql
    version: 10.13.8
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
  - name: rabbitmq
    version: 9.0.0
    repository: https://charts.bitnami.com/bitnami/
    condition: rabbitmq.enabled
  - name: memcached
    version: 6.0.21
    repository: https://charts.bitnami.com/bitnami/
    condition: memcached.enabled
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io
